sources:
  - { method: "<Main: java.lang.String source()>", type: "java.lang.String" }

sinks:
  - { method: "<Main: void sink(java.lang.String)>", index: 0 }


transfers:
 - { method: "<Main: byte[] Java_org_whispersystems_curve25519_NativeCurve25519Provider_generatePrivateKey(byte[])>", from: 0, to: result, type: "byte[]" }
 - { method: "<Main: byte[] Java_org_whispersystems_curve25519_NativeCurve25519Provider_generatePrivateKey(byte[])>", from: 0, to: result, type: "byte[]" }
 - { method: "<Main: byte[] Java_org_whispersystems_curve25519_NativeCurve25519Provider_generatePrivateKey(byte[])>", from: 0, to: result, type: "byte[]" }
 - { method: "<Main: byte[] Java_org_whispersystems_curve25519_NativeCurve25519Provider_generatePrivateKey(byte[])>", from: 0, to: result, type: "byte[]" }
 - { method: "<Main: byte[] Java_org_whispersystems_curve25519_NativeCurve25519Provider_generatePrivateKey(byte[])>", from: 0, to: result, type: "byte[]" }
 - { method: "<Main: byte[] Java_org_whispersystems_curve25519_NativeCurve25519Provider_generatePrivateKey(byte[])>", from: 0, to: result, type: "byte[]" }
 - { method: "<Main: byte[] Java_org_whispersystems_curve25519_NativeCurve25519Provider_generatePrivateKey(byte[])>", from: 0, to: result, type: "byte[]" }
 - { method: "<Main: byte[] Java_org_whispersystems_curve25519_NativeCurve25519Provider_generatePrivateKey(byte[])>", from: 0, to: result, type: "byte[]" }
