name: callersensitive-build

# Triggers the workflow on push or pull request events
on: [push, pull_request]

# Customize the env variable
env:
  SVF_CTIR: 1 
  SVF_Z3: 1
  SVF_DIR: $GITHUB_WORKSPACE

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
#         include:
#           - os: [ubuntu-18.04]
#             sanitizer: address
    steps:
      # checkout the repo
      - uses: actions/checkout@v2
#       - uses: actions/setup-java@v3
#         with:
#           distribution: 'zulu'
#           java-version: '17'
      # setup the environment
      - name: mac-setup
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 12.5.1
      - name: mac-setup-workaround
        if: runner.os == 'macOS'
        run: ln -sfn /Applications/Xcode_12.5.1.app /Applications/Xcode.app
      - name: ubuntu-setup
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install cmake gcc g++ nodejs doxygen graphviz lcov
      
#       # build-svf
#       - name: build-svf
#         run: |
#           cd $GITHUB_WORKSPACE
#           echo $(pwd)
#           if [ "${{matrix.sanitizer}}" != "" ]; then export SVF_SANITIZER="${{matrix.sanitizer}}"; fi
#           if [ "$RUNNER_OS" == "Linux" ] && [ "${{matrix.sanitizer}}" == "" ]; then export SVF_COVERAGE=1; fi
#           # git clone "https://github.com/SVF-tools/Test-Suite.git";
#           source ${{github.workspace}}/build.sh

      - name: just for test
        working-directory: ${{github.workspace}}
        run: |
          ls -l
          java -version
          echo ++++++++++++++++++++++++++
          wget https://github.com/shuangxiangkan/CallerSensitive-Tai-e/releases/download/0.0.1/CallerSensitive-tai-e.jar
          echo ++++++++++++++++++++++++++
          ls -l
          java -cp ./CallerSensitive-tai-e.jar pascal.taie.Main -cp SummaryTest-1.0-SNAPSHOT.jar Main -java 8 -a pta=taint-config:./test/taint-config.yml;action:dump;only-app:true
          echo ++++++++++++++++++++++++++
          ls -l
          python --version
          # java -version
          # source ./test.sh
 
      
